spring.application.name=orders-service
server.port=8082
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ordersdb}
spring.datasource.username=${DB_USERNAME:l7defense}
spring.datasource.password=${DB_PASSWORD:l7defense}
spring.jpa.hibernate.ddl-auto=update
spring.threads.virtual.enabled=true